### ISSUE TITLE
Wrong permissions for fossdash folder

### ISSUE THREAD

**Issue by NicolasToussaint** [darshank15/GSoC_2020_FOSSOlogy#8]
When deploying with Docker, the ownership and permission are wrong for folder `/srv/fossology/repository/fossdash`

Out of the box:
```
root@a508406c2e6b:/fossology# ls -l /srv/fossology/repository/
total 0
drwxr-xr-x 2 fossy fossy 6 Jul  7 08:28 fossdash
```

Turning on Fossdash export does not work, no log is produced.

Executing the script by hand shows an access error:
```
root@a508406c2e6b:/fossology# sudo -u  www-data python2 /usr/local/lib/fossology/fossdash-publish.py

2020-07-07 10:54:49.100796
publishing FossDash URL = http://influxdb:8086/write?db=fossology_db
Fossology Instance UUID =  6d7a21ba-6f43-4605-b720-a22260d3df65
All data metrics Generated
[Errno 13] Permission denied: '/srv/fossology/repository/fossdash/fossdash-publish.py.BIN58M'
```

Fixing man ually (no sure it's the perfect settings)
```
root@a508406c2e6b:/fossology# chown fossy:www-data /srv/fossology/repository/fossdash 
root@a508406c2e6b:/fossology# chmod g+w /srv/fossology/repository/fossdash
root@a508406c2e6b:/fossology# ls -l /srv/fossology/repository/
total 0
drwxrwxr-x 2 fossy www-data 6 Jul  7 08:28 fossdash
```

Re-running by hand, and automatic runs work well:
```
root@a508406c2e6b:/fossology# sudo -u  www-data python2 /usr/local/lib/fossology/fossdash-publish.py

2020-07-07 11:01:42.455665
publishing FossDash URL = http://influxdb:8086/write?db=fossology_db
Fossology Instance UUID =  6d7a21ba-6f43-4605-b720-a22260d3df65
All data metrics Generated
sending file to influxDB = /srv/fossology/repository/fossdash/fossdash-publish.py.OPXSYA
status code = 204
```

**Comment by darshank15** [comment]
This is now resolved 
Commit ID : https://github.com/Orange-OpenSource/fossology/pull/3/commits/33614caaf5e0924bf2620e08858a8be0bcb95eb8

**Comment by NicolasToussaint** [comment]
Related to #7 (that contains multiple tasks), about cleaning old files.

I still experienced an problem with Docker instances. I have in folder ` /srv/fossology/repository/fossdash/` :
```
-rw-r--r-- 1 www-data fossy   3351 Aug 14 15:14 fossdash-publish.20200814_151401.reported
-rw-r--r-- 1 www-data fossy   3351 Aug 14 15:15 fossdash-publish.20200814_151501.reported
-rw-r--r-- 1 www-data fossy 570998 Aug 14 15:15 fossdash.log
-rw-r--r-- 1 fossy    fossy      0 Aug 13 16:15 fossdash_clean_file_list
```

Fossdash.log:
```
2020-08-14 15:16:01.838137
Fossology Instance UUID =  fossology-dev-1
All data metrics Generated
publishing FossDash URL = http://influxdb:8086/write?db=fossology_db
sending file to influxDB = /srv/fossology/repository/fossdash/fossdash-publish.20200814_151601
user_pass authentication 
status code = 204
/bin/sh: 1: cannot create /srv/fossology/repository/fossdash/fossdash_clean_file_list: Permission denied
```
If I delete the file, it is recreated with correct `www-data fossy` permission

**Comment by darshank15** [comment]
Maybe It is due to .

you probably run script **manually** as FOSSY user.  OS will create a file and assigned default permission as `-rw-r--r--` with fossy as a user and fossy as a group.

When script run by CRON job. It runs as www-data ==> File doesn't have a group or user as www-data. So permission denied.

**Comment by NicolasToussaint** [comment]
Oh, very good point, @darshank15 : I probably ran the script with wrong user first :-/
Closing
